/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 * 
 * Physics engine for Electric Field and Electric Potential calculations.
 * Standard Coulomb constant: k_e = 1 / (4 * pi * epsilon_0) ≈ 8.9875517923e9 N·m²/C²
 * Elementary charge: e = 1.602176634e-19 C
 */

import { PointCharge, TestPoint, Vector3D, ChargeCalculation, TotalCalculation, ChargeUnit } from '../types';

export const COULOMB_CONSTANT = 8.9875517923e9; // N·m²/C²
export const ELEMENTARY_CHARGE = 1.602176634e-19; // C
export const EPSILON_0 = 8.8541878128e-12; // C²/(N·m²)
export const SINGULARITY_THRESHOLD = 1e-4; // 0.1 mm cutoff to avoid division by zero

/**
 * Converts a charge value in the given unit to Coulombs.
 */
export function chargeToCoulombs(q: number, unit: ChargeUnit): number {
  switch (unit) {
    case 'e':
      return q * ELEMENTARY_CHARGE;
    case 'uC':
      return q * 1e-6;
    case 'nC':
      return q * 1e-9;
    case 'C':
      return q;
    default:
      return q;
  }
}

/**
 * Converts Coulombs back to specified display unit.
 */
export function coulombsToUnit(coulombs: number, unit: ChargeUnit): number {
  switch (unit) {
    case 'e':
      return coulombs / ELEMENTARY_CHARGE;
    case 'uC':
      return coulombs / 1e-6;
    case 'nC':
      return coulombs / 1e-9;
    case 'C':
      return coulombs;
    default:
      return coulombs;
  }
}

/**
 * Calculates the electric field vector E at any given point in space (x, y, z)
 * generated by a collection of point charges.
 * E = sum( k_e * q_i / r_i^2 * r_hat_i ) = sum( k_e * q_i / r_i^3 * (r - r_i) )
 */
export function calculateElectricFieldAt(
  charges: PointCharge[],
  point: Vector3D
): Vector3D {
  let ex = 0;
  let ey = 0;
  let ez = 0;

  for (const c of charges) {
    const qC = chargeToCoulombs(c.q, c.unit);
    if (qC === 0) continue;

    const rx = point.x - c.x;
    const ry = point.y - c.y;
    const rz = point.z - (c.z || 0);

    const distSq = rx * rx + ry * ry + rz * rz;
    const dist = Math.sqrt(distSq);

    if (dist < SINGULARITY_THRESHOLD) continue;

    // E_i = (k_e * q_i / dist^3) * vec(R)
    const factor = (COULOMB_CONSTANT * qC) / (dist * dist * dist);
    ex += factor * rx;
    ey += factor * ry;
    ez += factor * rz;
  }

  return { x: ex, y: ey, z: ez };
}

/**
 * Calculates the electric potential V at any given point in space (x, y, z)
 * generated by a collection of point charges.
 * V = sum( k_e * q_i / r_i )
 */
export function calculatePotentialAt(
  charges: PointCharge[],
  point: Vector3D
): number {
  let vTotal = 0;

  for (const c of charges) {
    const qC = chargeToCoulombs(c.q, c.unit);
    if (qC === 0) continue;

    const rx = point.x - c.x;
    const ry = point.y - c.y;
    const rz = point.z - (c.z || 0);

    const dist = Math.sqrt(rx * rx + ry * ry + rz * rz);
    if (dist < SINGULARITY_THRESHOLD) continue;

    vTotal += (COULOMB_CONSTANT * qC) / dist;
  }

  return vTotal;
}

/**
 * Computes the full step-by-step calculation table for a test point,
 * breaking down each charge's contribution according to the Lab guide requirements.
 */
export function computeDetailedCalculations(
  charges: PointCharge[],
  testPoint: TestPoint
): TotalCalculation {
  const calculations: ChargeCalculation[] = [];
  let totalEx = 0;
  let totalEy = 0;
  let totalEz = 0;
  let totalV = 0;

  for (const charge of charges) {
    const qC = chargeToCoulombs(charge.q, charge.unit);
    const cz = charge.z || 0;

    // Vector from charge to test point: R = r_0 - r_i
    const rx = testPoint.x - charge.x;
    const ry = testPoint.y - charge.y;
    const rz = testPoint.z - cz;

    const distance = Math.sqrt(rx * rx + ry * ry + rz * rz);

    let unitVector: Vector3D = { x: 0, y: 0, z: 0 };
    let electricField: Vector3D = { x: 0, y: 0, z: 0 };
    let fieldMagnitude = 0;
    let potential = 0;

    if (distance >= SINGULARITY_THRESHOLD && qC !== 0) {
      unitVector = {
        x: rx / distance,
        y: ry / distance,
        z: rz / distance,
      };

      const eFactor = (COULOMB_CONSTANT * qC) / (distance * distance * distance);
      electricField = {
        x: eFactor * rx,
        y: eFactor * ry,
        z: eFactor * rz,
      };

      fieldMagnitude = Math.sqrt(
        electricField.x * electricField.x +
        electricField.y * electricField.y +
        electricField.z * electricField.z
      );

      potential = (COULOMB_CONSTANT * qC) / distance;
    }

    totalEx += electricField.x;
    totalEy += electricField.y;
    totalEz += electricField.z;
    totalV += potential;

    calculations.push({
      charge,
      qInCoulombs: qC,
      relPos: { x: rx, y: ry, z: rz },
      distance,
      unitVector,
      electricField,
      fieldMagnitude,
      potential,
    });
  }

  const totalMagnitude = Math.sqrt(totalEx * totalEx + totalEy * totalEy + totalEz * totalEz);
  const angle2D = Math.atan2(totalEy, totalEx) * (180 / Math.PI);

  return {
    testPoint,
    chargesCalculations: calculations,
    totalElectricField: { x: totalEx, y: totalEy, z: totalEz },
    totalFieldMagnitude: totalMagnitude,
    fieldAngle2D: angle2D,
    totalPotential: totalV,
  };
}

/**
 * Calculates 2D electric field lines by integrating along the field vector direction.
 */
export interface FieldLinePoint {
  x: number;
  y: number;
}

export function traceFieldLines2D(
  charges: PointCharge[],
  bounds: { minX: number; maxX: number; minY: number; maxY: number },
  linesPerCharge: number = 16,
  maxSteps: number = 250,
  stepSize: number = 0.015
): FieldLinePoint[][] {
  const lines: FieldLinePoint[][] = [];
  if (charges.length === 0) return lines;

  // For each charge, start rays
  for (const c of charges) {
    const isPositive = c.q > 0;
    const isNegative = c.q < 0;
    if (!isPositive && !isNegative) continue;

    // Amount of lines proportional to charge magnitude
    const rayCount = Math.max(8, Math.min(32, Math.round(linesPerCharge * Math.abs(c.q))));
    const startRadius = 0.04; // 4 cm from center

    for (let i = 0; i < rayCount; i++) {
      const angle = (i * 2 * Math.PI) / rayCount;
      let currX = c.x + Math.cos(angle) * startRadius;
      let currY = c.y + Math.sin(angle) * startRadius;

      const path: FieldLinePoint[] = [{ x: currX, y: currY }];
      const directionSign = isPositive ? 1 : -1; // Positive radiates out, negative traces backward

      for (let step = 0; step < maxSteps; step++) {
        const field = calculateElectricFieldAt(charges, { x: currX, y: currY, z: 0 });
        const mag = Math.sqrt(field.x * field.x + field.y * field.y);

        if (mag < 1e-12 || !isFinite(mag)) break;

        // Unit field direction
        const dirX = (field.x / mag) * directionSign;
        const dirY = (field.y / mag) * directionSign;

        // Runge-Kutta 2 (Midpoint step) for smooth curves
        const midX = currX + dirX * (stepSize * 0.5);
        const midY = currY + dirY * (stepSize * 0.5);

        const midField = calculateElectricFieldAt(charges, { x: midX, y: midY, z: 0 });
        const midMag = Math.sqrt(midField.x * midField.x + midField.y * midField.y);
        if (midMag < 1e-12 || !isFinite(midMag)) break;

        const actualDirX = (midField.x / midMag) * directionSign;
        const actualDirY = (midField.y / midMag) * directionSign;

        currX += actualDirX * stepSize;
        currY += actualDirY * stepSize;

        path.push({ x: currX, y: currY });

        // Check if out of bounds
        if (
          currX < bounds.minX ||
          currX > bounds.maxX ||
          currY < bounds.minY ||
          currY > bounds.maxY
        ) {
          break;
        }

        // Check if hit another charge (sink / source)
        let hitOther = false;
        for (const other of charges) {
          if (other.id === c.id) continue;
          const dx = currX - other.x;
          const dy = currY - other.y;
          if (Math.sqrt(dx * dx + dy * dy) < startRadius * 0.8) {
            hitOther = true;
            break;
          }
        }
        if (hitOther) break;
      }

      if (path.length > 2) {
        lines.push(path);
      }
    }
  }

  return lines;
}

/**
 * Format a number into clean scientific or decimal notation
 */
export function formatPhysicsValue(
  value: number,
  unitSuffix: string = '',
  scientific: boolean = false,
  precision: number = 4
): string {
  if (value === 0 || !isFinite(value) || isNaN(value)) {
    return `0.0000 ${unitSuffix}`.trim();
  }

  const absVal = Math.abs(value);

  if (scientific || absVal >= 1e5 || (absVal < 1e-3 && absVal > 0)) {
    const expStr = value.toExponential(precision);
    const [coeff, exp] = expStr.split('e');
    const expNum = parseInt(exp, 10);
    return `${coeff} × 10${toSuperscript(expNum)} ${unitSuffix}`.trim();
  } else {
    return `${value.toFixed(precision)} ${unitSuffix}`.trim();
  }
}

/**
 * Convert integer exponent to superscript string e.g. 3 -> "³", -5 -> "⁻⁵"
 */
function toSuperscript(num: number): string {
  const digits: { [k: string]: string } = {
    '0': '⁰',
    '1': '¹',
    '2': '²',
    '3': '³',
    '4': '⁴',
    '5': '⁵',
    '6': '⁶',
    '7': '⁷',
    '8': '⁸',
    '9': '⁹',
    '-': '⁻',
    '+': '⁺',
  };
  return num
    .toString()
    .split('')
    .map((c) => digits[c] || c)
    .join('');
}
