/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 * 
 * Presets matching the Universidad de Talca "Laboratorio N° 1: Campo Eléctrico y Potencial Eléctrico"
 * plus standard educational configurations.
 */

import { LabPreset } from '../types';

export const LAB_PRESETS: LabPreset[] = [
  {
    id: 'actividad-1',
    title: 'Actividad 1: Campo Eléctrico Total',
    subtitle: 'Laboratorio N° 1 - Guía Oficial',
    description: 'Sistema de 3 cargas de magnitud |e| para determinar el vector campo eléctrico individual y total en el origen (0,0).',
    activityNumber: 1,
    dimension: '2D',
    chargeUnit: 'e',
    coordinateRange: 1.0,
    testPoint: { x: 0, y: 0, z: 0 },
    charges: [
      {
        id: 'q1',
        name: 'q₁ (+e)',
        x: 0.00,
        y: 0.50,
        z: 0,
        q: 1,
        unit: 'e',
        color: '#ef4444',
      },
      {
        id: 'q2',
        name: 'q₂ (-e)',
        x: 0.50,
        y: 0.00,
        z: 0,
        q: -1,
        unit: 'e',
        color: '#3b82f6',
      },
      {
        id: 'q3',
        name: 'q₃ (+e)',
        x: -0.50,
        y: -0.25,
        z: 0,
        q: 1,
        unit: 'e',
        color: '#ef4444',
      },
    ],
  },
  {
    id: 'actividad-2',
    title: 'Actividad 2: Potencial Eléctrico Total',
    subtitle: 'Laboratorio N° 1 - Guía Oficial',
    description: 'Sistema de 3 cargas de magnitudes |e|, |2e| y |4e| para determinar el potencial eléctrico escalar individual y total en (0,0).',
    activityNumber: 2,
    dimension: '2D',
    chargeUnit: 'e',
    coordinateRange: 1.0,
    testPoint: { x: 0, y: 0, z: 0 },
    charges: [
      {
        id: 'q1',
        name: 'q₁ (+4e)',
        x: -0.25,
        y: -0.25,
        z: 0,
        q: 4,
        unit: 'e',
        color: '#ef4444',
      },
      {
        id: 'q2',
        name: 'q₂ (-2e)',
        x: 0.55,
        y: -0.45,
        z: 0,
        q: -2,
        unit: 'e',
        color: '#3b82f6',
      },
      {
        id: 'q3',
        name: 'q₃ (-e)',
        x: -0.45,
        y: 0.30,
        z: 0,
        q: -1,
        unit: 'e',
        color: '#3b82f6',
      },
    ],
  },
  {
    id: 'dipolo-2d',
    title: 'Dipolo Eléctrico (2D)',
    subtitle: 'Configuración fundamental',
    description: 'Dos cargas de igual magnitud y signos opuestos (+q, -q). Observa la simetría de las líneas de campo y las superficies equipotenciales.',
    dimension: '2D',
    chargeUnit: 'uC',
    coordinateRange: 1.0,
    testPoint: { x: 0, y: 0.35, z: 0 },
    charges: [
      {
        id: 'q1',
        name: 'q₁ (+1 µC)',
        x: -0.30,
        y: 0.00,
        z: 0,
        q: 1,
        unit: 'uC',
        color: '#ef4444',
      },
      {
        id: 'q2',
        name: 'q₂ (-1 µC)',
        x: 0.30,
        y: 0.00,
        z: 0,
        q: -1,
        unit: 'uC',
        color: '#3b82f6',
      },
    ],
  },
  {
    id: 'cuadrupolo-2d',
    title: 'Cuadrupolo Eléctrico (2D)',
    subtitle: 'Arreglo de 4 cargas en cuadrilátero',
    description: 'Cuatro cargas alternadas con simetría cuadrupolar. El campo decae con r⁴ a grandes distancias.',
    dimension: '2D',
    chargeUnit: 'uC',
    coordinateRange: 1.0,
    testPoint: { x: 0, y: 0, z: 0 },
    charges: [
      {
        id: 'q1',
        name: 'q₁ (+1 µC)',
        x: -0.35,
        y: 0.35,
        z: 0,
        q: 1,
        unit: 'uC',
        color: '#ef4444',
      },
      {
        id: 'q2',
        name: 'q₂ (-1 µC)',
        x: 0.35,
        y: 0.35,
        z: 0,
        q: -1,
        unit: 'uC',
        color: '#3b82f6',
      },
      {
        id: 'q3',
        name: 'q₃ (+1 µC)',
        x: 0.35,
        y: -0.35,
        z: 0,
        q: 1,
        unit: 'uC',
        color: '#ef4444',
      },
      {
        id: 'q4',
        name: 'q₄ (-1 µC)',
        x: -0.35,
        y: -0.35,
        z: 0,
        q: -1,
        unit: 'uC',
        color: '#3b82f6',
      },
    ],
  },
  {
    id: 'espacio-3d-dipolo',
    title: 'Dipolo Tridimensional (3D)',
    subtitle: 'Exploración en el espacio 3D',
    description: 'Visualiza el vector campo eléctrico y el potencial en cualquier coordenada tridimensional (x, y, z) con rotación libre.',
    dimension: '3D',
    chargeUnit: 'uC',
    coordinateRange: 1.5,
    testPoint: { x: 0.3, y: 0.4, z: 0.2 },
    charges: [
      {
        id: 'q1',
        name: 'q₁ (+2 µC)',
        x: 0.00,
        y: 0.45,
        z: 0.00,
        q: 2,
        unit: 'uC',
        color: '#ef4444',
      },
      {
        id: 'q2',
        name: 'q₂ (-2 µC)',
        x: 0.00,
        y: -0.45,
        z: 0.00,
        q: -2,
        unit: 'uC',
        color: '#3b82f6',
      },
      {
        id: 'q3',
        name: 'q₃ (+1 µC)',
        x: 0.50,
        y: 0.00,
        z: 0.30,
        q: 1,
        unit: 'uC',
        color: '#ef4444',
      },
    ],
  },
];
